Set t=Rastr
Set gen = t.Tables("Generator")
Set node = t.Tables("node")

Set node_gen = gen.Cols("Node")
Set sel_gen = gen.Cols("sel")

MaxRowGen = gen.Count

for i=0 to MaxRowGen-1
    p_gen = gen.Cols("P").Z(i)
    p_nom = gen.Cols("Pnom").Z(i)
    if p_gen > p_nom Then
        sel_gen.Z(i) = 1
    End if
next