
r=setlocale("en-us")
rrr=1


set t=RASTR


set vet=t.tables("vetv")
set uzl=t.tables("node")
set gen=t.Tables("Generator")
set vozb=t.Tables("Exciter")
set arv=t.Tables("ExcControl")
set vieee=t.Tables("DFWIEEE421")
set stieee=t.Tables("DFWIEEE421PSS13")
set pss4	=t.Tables("DFWIEEE421PSS4B")
set ars=Rastr.Tables("ARS")
set forc=Rastr.Tables("Forcer")
set omv=t.Tables("DFW421UEL")
set bor=t.Tables("DFWOELUNITROL")
set FuncPQ=t.Tables("FuncPQ")

set nsta	=gen.Cols("sta")
set numg	=gen.Cols("Num")
set nameg	=gen.Cols("Name")
set gNumBrand = gen.Cols("NumBrand")
set nodeg	=gen.Cols("Node")
set ExciterId=gen.Cols("ExciterId")
set ARSId=gen.Cols("ARSId")
set pgen	=gen.Cols("P")
set ModelType	=gen.Cols("ModelType")
set pnom	=gen.Cols("Pnom")
set unom	=gen.Cols("Ugnom")
set cosfi	=gen.Cols("cosFi")
set Demp	=gen.Cols("Demp")
set mj		=gen.Cols("Mj")
set xd1		=gen.Cols("xd1")
set Qmin	=gen.Cols("Qmin")
set Qmax	=gen.Cols("Qmax")
'set nodeld	=gen.Cols("nodeld")
set xd1	=gen.Cols("xd1")
set xd	=gen.Cols("xd")
set xq	=gen.Cols("xq")
set xd2	=gen.Cols("xd2")
set xq2	=gen.Cols("xq2")
set td01	=gen.Cols("td01")
set td02	=gen.Cols("td02")
set tq02	=gen.Cols("tq02")
set xq1	=gen.Cols("xq1")
set xl	=gen.Cols("xl")
set x2	=gen.Cols("x2")
set x2	=gen.Cols("x0")
set tq01	=gen.Cols("tq01")
set gIVActuatorId	=gen.Cols("IVActuatorId")
set Pmax	=gen.Cols("Pmax")



set ny		=uzl.Cols("ny")
set name	=uzl.Cols("name")
set pg		=uzl.Cols("pg") 
set tip		=uzl.Cols("tip") 
set nqmin	=uzl.Cols("qmin")
set nqmax	=uzl.Cols("qmax")
set uhom	=uzl.Cols("uhom")

set idv	=vozb.Cols("Id")
set namev	=vozb.Cols("Name")
set ModelTypev	=vozb.Cols("ModelType")
set Brandv	=vozb.Cols("Brand")
set ExcControlIdv	=vozb.Cols("ExcControlId")
set ForcerIdv	=vozb.Cols("ForcerId")
set Texcv	=vozb.Cols("Texc")
set Kig=vozb.Cols("Kig")
set Kif=vozb.Cols("Kif")
set Uf_min=vozb.Cols("Uf_min")
set Uf_max=vozb.Cols("Uf_max")
set If_min=vozb.Cols("If_min")
set If_max=vozb.Cols("If_max")
set Type_rgv=vozb.Cols("Type_rg")


set ida	=arv.Cols("Id")
set namea	=arv.Cols("Name")
set ModelTypea	=arv.Cols("ModelType")
set Branda	=arv.Cols("Brand")
set Trv	=arv.Cols("Trv")
set Ku	=arv.Cols("Ku")
set Ku1	=arv.Cols("Ku1")
set Kif1	=arv.Cols("Kif1")
set Kf	=arv.Cols("Kf")
set Kf1	=arv.Cols("Kf1")
set Tf	=arv.Cols("Tf")
set Urv_min	=arv.Cols("Urv_min")
set Urv_max	=arv.Cols("Urv_max")
set Alpha	=arv.Cols("Alpha")


set ids	=ars.Cols("Id")
set names	=ars.Cols("Name")
set ModelTypes	=ars.Cols("ModelType")
set Brands	=ars.Cols("Brand")
set ao	=ars.Cols("ao")
set az	=ars.Cols("az")
set otmin	=ars.Cols("otmin")
set otmax	=ars.Cols("otmax")
set strs	=ars.Cols("strs")
set zn	=ars.Cols("zn")



set idf	=forc.Cols("Id")
set namef	=forc.Cols("Name")
set ModelTypef	=forc.Cols("ModelType")
set Ubf	=forc.Cols("Ubf")
set Uef	=forc.Cols("Uef")
set Rf	=forc.Cols("Rf")
set Texc_f	=forc.Cols("Texc_f")
set Tz_in	=forc.Cols("Tz_in")
set Tz_out	=forc.Cols("Tz_out")
set Ubrf	=forc.Cols("Ubrf")
set Uerf	=forc.Cols("Uerf")
set Rrf	=forc.Cols("Rrf")
set Texc_rf	=forc.Cols("Texc_rf")


set ststa=stieee.Cols("sta")
set stId=stieee.Cols("Id")
set stName=stieee.Cols("Name")
set stModel=stieee.Cols("ModelType")
set stBrand=stieee.Cols("Brand")
set stCustomModel=stieee.Cols("CustomModel")
set stInput1Type=stieee.Cols("Input1Type")
set stInput2Type=stieee.Cols("Input2Type")
set stVstmin=stieee.Cols("Vstmin")
set stVstmax=stieee.Cols("Vstmax")
set stKs1=stieee.Cols("Ks1")
set stT1=stieee.Cols("T1")
set stT2=stieee.Cols("T2")
set stT3=stieee.Cols("T3")
set stT4=stieee.Cols("T4")
set stT5=stieee.Cols("T5")
set stT6=stieee.Cols("T6")
set stT7=stieee.Cols("T7")
set stT8=stieee.Cols("T8")
set stT9=stieee.Cols("T9")
set stT10=stieee.Cols("T10")
set stT11=stieee.Cols("T11")
set stA1=stieee.Cols("A1")
set stA2=stieee.Cols("A2")
set stA3=stieee.Cols("A3")
set stA4=stieee.Cols("A4")
set stA5=stieee.Cols("A5")
set stA6=stieee.Cols("A6")
set stA7=stieee.Cols("A7")
set stA8=stieee.Cols("A8")
set stKs2=stieee.Cols("Ks2")
set stKs3=stieee.Cols("Ks3")
set stTw1=stieee.Cols("Tw1")
set stTw2=stieee.Cols("Tw2")
set stTw3=stieee.Cols("Tw3")
set stTw4=stieee.Cols("Tw4")
set stM=stieee.Cols("M")
set stN=stieee.Cols("N")
set stVsi1min=stieee.Cols("Vsi1min")
set stVsi1max=stieee.Cols("Vsi1max")
set stVsi2min=stieee.Cols("Vsi2min")
set stVsi2max=stieee.Cols("Vsi2max")


set vista=vieee.Cols("sta")
set viId=vieee.Cols("Id")
set viName=vieee.Cols("Name")
set viModel=vieee.Cols("ModelType")
set viBrand=vieee.Cols("Brand")
set viCustomModel=vieee.Cols("CustomModel")
set viUELId=vieee.Cols("UELId")
set viUELPos=vieee.Cols("UELPos")
set viOELId=vieee.Cols("OELId")
set viOELPos=vieee.Cols("OELPos")
set viPSSId=vieee.Cols("PSSId")
set viPSSPos=vieee.Cols("PSSPos")
set viTe=vieee.Cols("Te")
set viKe=vieee.Cols("Ke")
set viSe1=vieee.Cols("Se1")
set viEfd1=vieee.Cols("Efd1")
set viVe1=vieee.Cols("Ve1")
set viSe2=vieee.Cols("Se2")
set viEfd2=vieee.Cols("Efd2")
set viVe2=vieee.Cols("Ve2")
set viVemin=vieee.Cols("Vemin")
set viVrmin=vieee.Cols("Vrmin")
set viVrmax=vieee.Cols("Vrmax")
set viKa=vieee.Cols("Ka")
set viTa=vieee.Cols("Ta")
set viTf=vieee.Cols("Tf")
set viKf=vieee.Cols("Kf")
set viTc=vieee.Cols("Tc")
set viTb=vieee.Cols("Tb")
set viKv=vieee.Cols("Kv")
set viTrh=vieee.Cols("Trh")
set viKpr=vieee.Cols("Kpr")
set viKir=vieee.Cols("Kir")
set viKdr=vieee.Cols("Kdr")
set viTdr=vieee.Cols("Tdr")
set viKc=vieee.Cols("Kc")
set viKd=vieee.Cols("Kd")
set viVfemax=vieee.Cols("Vfemax")
set viVamin=vieee.Cols("Vamin")
set viVamax=vieee.Cols("Vamax")
set viKb=vieee.Cols("Kb")
set viKh=vieee.Cols("Kh")
set viKr=vieee.Cols("Kr")
set viKn=vieee.Cols("Kn")
set viEfdn=vieee.Cols("Efdn")
set viKlv=vieee.Cols("Klv")
set viVlv=vieee.Cols("Vlv")
set viVimin=vieee.Cols("Vimin")
set viVimax=vieee.Cols("Vimax")
set viTf2=vieee.Cols("Tf2")
set viTf3=vieee.Cols("Tf3")
set viTk=vieee.Cols("Tk")
set viTj=vieee.Cols("Tj")
set viTh=vieee.Cols("Th")
set viVhmax=vieee.Cols("Vhmax")
set viVfelim=vieee.Cols("Vfelim")
set viKp=vieee.Cols("Kp")
set viKpa=vieee.Cols("Kpa")
set viKia=vieee.Cols("Kia")
set viKf1=vieee.Cols("Kf1")
set viKf2=vieee.Cols("Kf2")
set viKl=vieee.Cols("Kl")
set viTb1=vieee.Cols("Tb1")
set viTc1=vieee.Cols("Tc1")
set viKlr=vieee.Cols("Klr")
set viIlr=vieee.Cols("Ilr")
set viKi=vieee.Cols("Ki")
set viTheta=vieee.Cols("Theta")
set viVmmin=vieee.Cols("Vmmin")
set viVmmax=vieee.Cols("Vmmax")
set viKg=vieee.Cols("Kg")
set viVBmax=vieee.Cols("VBmax")
set viVGmax=vieee.Cols("VGmax")
set viXl=vieee.Cols("Xl")
set viKm=vieee.Cols("Km")
set viTm=vieee.Cols("Tm")
set viTb2=vieee.Cols("Tb2")
set viTc2=vieee.Cols("Tc2")
set viTub1=vieee.Cols("Tub1")
set viTuc1=vieee.Cols("Tuc1")
set viTub2=vieee.Cols("Tub2")
set viTuc2=vieee.Cols("Tuc2")
set viTob1=vieee.Cols("Tob1")
set viToc1=vieee.Cols("Toc1")
set viTob2=vieee.Cols("Tob2")
set viToc2=vieee.Cols("Toc2")

set pss4sta=pss4.Cols("sta")
set pss4Id=pss4.Cols("Id")
set pss4Name=pss4.Cols("Name")
set pss4ModelType=pss4.Cols("ModelType")
set pss4Brand=pss4.Cols("Brand")
set pss4CustomModel=pss4.Cols("CustomModel")
set pss4Input1Type=pss4.Cols("Input1Type")
set pss4Input2Type=pss4.Cols("Input2Type")
set pss4MBPSS1=pss4.Cols("MBPSS1")
set pss4MBPSS2=pss4.Cols("MBPSS2")
set pss4Vstmin=pss4.Cols("Vstmin")
set pss4Vstmax=pss4.Cols("Vstmax")
set pss4KL1=pss4.Cols("KL1")
set pss4KL2=pss4.Cols("KL2")
set pss4KL11=pss4.Cols("KL11")
set pss4KL17=pss4.Cols("KL17")
set pss4TL1=pss4.Cols("TL1")
set pss4TL2=pss4.Cols("TL2")
set pss4TL3=pss4.Cols("TL3")
set pss4TL4=pss4.Cols("TL4")
set pss4TL5=pss4.Cols("TL5")
set pss4TL6=pss4.Cols("TL6")
set pss4TL7=pss4.Cols("TL7")
set pss4TL8=pss4.Cols("TL8")
set pss4TL9=pss4.Cols("TL9")
set pss4TL10=pss4.Cols("TL10")
set pss4TL11=pss4.Cols("TL11")
set pss4TL12=pss4.Cols("TL12")
set pss4KL=pss4.Cols("KL")
set pss4Vlmin=pss4.Cols("Vlmin")
set pss4Vlmax=pss4.Cols("Vlmax")
set pss4KI1=pss4.Cols("KI1")
set pss4KI2=pss4.Cols("KI2")
set pss4KI11=pss4.Cols("KI11")
set pss4KI17=pss4.Cols("KI17")
set pss4TI1=pss4.Cols("TI1")
set pss4TI2=pss4.Cols("TI2")
set pss4TI3=pss4.Cols("TI3")
set pss4TI4=pss4.Cols("TI4")
set pss4TI5=pss4.Cols("TI5")
set pss4TI6=pss4.Cols("TI6")
set pss4TI7=pss4.Cols("TI7")
set pss4TI8=pss4.Cols("TI8")
set pss4TI9=pss4.Cols("TI9")
set pss4TI10=pss4.Cols("TI10")
set pss4TI11=pss4.Cols("TI11")
set pss4TI12=pss4.Cols("TI12")
set pss4KI=pss4.Cols("KI")
set pss4Vimin=pss4.Cols("Vimin")
set pss4Vimax=pss4.Cols("Vimax")
set pss4KH1=pss4.Cols("KH1")
set pss4KH2=pss4.Cols("KH2")
set pss4KH11=pss4.Cols("KH11")
set pss4KH17=pss4.Cols("KH17")
set pss4TH1=pss4.Cols("TH1")
set pss4TH2=pss4.Cols("TH2")
set pss4TH3=pss4.Cols("TH3")
set pss4TH4=pss4.Cols("TH4")
set pss4TH5=pss4.Cols("TH5")
set pss4TH6=pss4.Cols("TH6")
set pss4TH7=pss4.Cols("TH7")
set pss4TH8=pss4.Cols("TH8")
set pss4TH9=pss4.Cols("TH9")
set pss4TH10=pss4.Cols("TH10")
set pss4TH11=pss4.Cols("TH11")
set pss4TH12=pss4.Cols("TH12")
set pss4KH=pss4.Cols("KH")
set pss4Vhmin=pss4.Cols("Vhmin")
set pss4Vhmax=pss4.Cols("Vhmax")
set pss4sta=pss4.Cols("sta")



set omvsta=omv.Cols("sta")
set omvId=omv.Cols("Id")
set omvName=omv.Cols("Name")
set omvModelType=omv.Cols("ModelType")
set omvBrand=omv.Cols("Brand")
set omvCustomModel=omv.Cols("CustomModel")
set omvTu1=omv.Cols("Tu1")
set omvTu2=omv.Cols("Tu2")
set omvTu3=omv.Cols("Tu3")
set omvTu4=omv.Cols("Tu4")
set omvVulmin=omv.Cols("Vulmin")
set omvVulmax=omv.Cols("Vulmax")
set omvKul=omv.Cols("Kul")
set omvKui=omv.Cols("Kui")
set omvVuimin=omv.Cols("Vuimin")
set omvVuimax=omv.Cols("Vuimax")
set omvKuf=omv.Cols("Kuf")
set omvTuf=omv.Cols("Tuf")
set omvKur=omv.Cols("Kur")
set omvKuc=omv.Cols("Kuc")
set omvVurmax=omv.Cols("Vurmax")
set omvVucmax=omv.Cols("Vucmax")
set omvTuV=omv.Cols("TuV")
set omvTuP=omv.Cols("TuP")
set omvTuQ=omv.Cols("TuQ")
set omvK1=omv.Cols("K1")
set omvK2=omv.Cols("K2")
set omvDependency_F1=omv.Cols("Dependency_F1")
set omvOutput=omv.Cols("Output")
set omvKl=omv.Cols("Kl")

set borsta=bor.Cols("sta")
set borId=bor.Cols("Id")
set borName=bor.Cols("Name")
set borModelType=bor.Cols("ModelType")
set borBrand=bor.Cols("Brand")
set borCustomModel=bor.Cols("CustomModel")
set borIfMax=bor.Cols("IfMax")
set borIfth=bor.Cols("Ifth")
set borKexpIf=bor.Cols("KexpIf")
set borKR3=bor.Cols("KR3")
set borKR3i=bor.Cols("KR3i")
set borTc23=bor.Cols("Tc23")
set borTb23=bor.Cols("Tb23")
set borTc13=bor.Cols("Tc13")
set borTb13=bor.Cols("Tb13")
set borVamin=bor.Cols("Vamin")
set borVamax=bor.Cols("Vamax")
set borTdel=bor.Cols("Tdel")
set borKth=bor.Cols("Kth")
set borKToF=bor.Cols("KToF")
set borKcF=bor.Cols("KcF")
set borKhF=bor.Cols("KhF")
set borTRFout=bor.Cols("TRFout")
set borTr=bor.Cols("Tr")
set borOutput=bor.Cols("Output")
set borKl=bor.Cols("Kl")

set FuncPQId=FuncPQ.Cols("Id")
set FuncPQP=FuncPQ.Cols("P")
set FuncPQQ=FuncPQ.Cols("Q")
flag=0
if flag=1 then
gen.SetSel "ModelType=0"
jj=gen.findnextsel(-1)
while jj<>-1
    uzl.SetSel "ny=" & nodeg.Z(jj)
    j1=uzl.FindNextSel (-1)

    if j1<>-1 then
    ModelType.Z(jj)=3
    If ABS(Pmax.Z(jj))>0 then
    pnom.Z(jj)=ABS(Pmax.Z(jj))
    else
    pnom.Z(jj)=ABS(Qmax.Z(jj))
    end if

    unom.Z(jj)=uzl.Cols("uhom").z(j1)

    cosfi.Z(jj)=0.85
    Demp.Z(jj)=5
    mj.Z(j2)=5*pnom.Z(jj)/cosfi.Z(jj)
    if pnom.Z(jj)=0 then
    pnom.Z(jj)=pgen.Z(jj)
    end if
    if pgen.Z(jj)=0 then
    pnom.Z(jj)=10
    end if
    xd1.Z(jj)=0.3*unom.Z(jj)*unom.Z(jj)*cosfi.Z(jj)/pnom.Z(jj)
    end if

    gen.SetSel "ModelType=0"
    jj=gen.FindNextSel (jj)
wend
end if 

MaxRowGen = gen.Count
flag2=1
if flag2=1 then 
    for i=0 to MaxRowGen-1
        if mj.Z(i) = 0 or 0 < mj.Z(i) < 0.00000001 then
            t.Printp("До mj.Z(i)" & mj.Z(i))
            mj.Z(i)=5*ABS(pnom.Z(i))/cosfi.Z(i)
            t.Printp(" После mj.Z(i)" & mj.Z(i))
        end if
    next
end if

flag3=0
if flag3=1 then 
for i=0 to MaxRowGen-1
    if pnom.Z(i)<0 then
        p_nom = pnom.Z(i)
        pnom.Z(i) = p_nom * (-1)
    end if  
next
end if 

flag4=0
if flag4=1 then 
for i=0 to MaxRowGen-1
    if xd1.Z(i)<0 then
        x_d_1 = xd1.Z(i)
        xd1.Z(i) = x_d_1 * (-1)
    end if  
next
end if 